version: '3'

services:
  ruby:
    build:
      context: ./
      dockerfile: docker/ruby/Dockerfile
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=study_rails
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql-volume:/var/lib/mysql:rw

volumes:
  mysql-volume:
