version: '3'

services:
  ruby:
    build:
      context: ./
      dockerfile: docker/ruby/Dockerfile
    command: bin/rails server -b 0.0.0.0 -p 3000
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./:/app:cached
    depends_on:
      - mysql

  mysql:
    build:
      context: ./
      dockerfile: ./docker/mysql/Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql-volume:/var/lib/mysql:rw

volumes:
  mysql-volume:
