version: '3'

services:
  ruby:
    build:
      context: ./
      dockerfile: docker/ruby/Dockerfile
    command: bin/rails server -b 0.0.0.0 -p 8000
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ./:/app:cached
    depends_on:
      - mysql

  mysql:
    build:
      context: ./
      dockerfile: ./docker/mysql/Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql-volume:/var/lib/mysql:rw

  node:
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
    command: yarn dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app:cached
    depends_on:
      - ruby

volumes:
  mysql-volume:
